import { NextResponse } from "next/server"

export async function POST(req: Request) {
  try {
    const { project } = await req.json()

    if (!project || !project.name) {
      return NextResponse.json({ error: "Project data is required" }, { status: 400 })
    }

    const code = generateProjectCode(project)

    const zipBuffer = await generateZip(project.name, code)

    return new NextResponse(zipBuffer as unknown as BodyInit, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${project.name.replace(/\s+/g, "-").toLowerCase()}.zip"`,
      },
    })
  } catch (error) {
    return NextResponse.json({ error: "Download failed" }, { status: 500 })
  }
}

function generateProjectCode(project: any) {
  const { name, theme, pages } = project
  const sections = pages?.[0]?.sections || []

  const sectionComponents = sections
    .filter((s: any) => s.type !== "Footer")
    .map((s: any) => {
      const props = JSON.stringify(s.props || {}, null, 6)
        .replace(/"([^"]+)":/g, "$1:")
      return `      <${s.type} {...${props}} />`
    })
    .join("\n")

  return {
    "package.json": JSON.stringify({
      name: name.toLowerCase().replace(/\s+/g, "-"),
      version: "1.0.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start" },
      dependencies: {
        next: "16.2.10", react: "19.2.4", "react-dom": "19.2.4",
        "framer-motion": "^12.0.0", "lucide-react": "^0.500.0",
      },
      devDependencies: {
        typescript: "^5.0.0", "@types/node": "^20", "@types/react": "^19", "@types/react-dom": "^19",
        tailwindcss: "^4.0.0", "@tailwindcss/postcss": "^4",
      },
    }, null, 2),
    "next.config.js": `/** @type {import('next').NextConfig} */\nconst nextConfig = {}\nmodule.exports = nextConfig`,
    "tsconfig.json": JSON.stringify({
      compilerOptions: {
        target: "ES2017", lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true, skipLibCheck: true, strict: true, noEmit: true,
        esModuleInterop: true, module: "esnext", moduleResolution: "bundler",
        resolveJsonModule: true, isolatedModules: true, jsx: "preserve",
        incremental: true, plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    }, null, 2),
    "postcss.config.js": `module.exports = { plugins: { '@tailwindcss/postcss': {} } }`,
    "src/app/globals.css": `@import "tailwindcss";\n\n@theme {\n  --color-primary: ${theme?.colors?.primary || "#7C3AED"};\n  --color-secondary: ${theme?.colors?.secondary || "#06B6D4"};\n  --color-bg: ${theme?.colors?.background || "#030712"};\n  --color-surface: ${theme?.colors?.surface || "#111827"};\n  --color-text: ${theme?.colors?.text || "#F9FAFB"};\n}\n\nbody {\n  background-color: var(--color-bg);\n  color: var(--color-text);\n  font-family: '${theme?.fonts?.body || "DM Sans"}', sans-serif;\n}`,
    "src/app/layout.tsx": `import type { Metadata } from "next"\nimport "./globals.css"\n\nexport const metadata: Metadata = {\n  title: "${name}",\n  description: "Generated by BuildAI.Sites",\n}\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  )\n}`,
    "src/app/page.tsx": `"use client"\n\nimport { motion } from "framer-motion"\n\n${sections.map((s: any) => `function ${s.type}(props: any) {\n  return (\n    <section className="py-20 px-4">\n      <div className="max-w-6xl mx-auto">\n        <motion.div\n          initial={{ opacity: 0, y: 20 }}\n          whileInView={{ opacity: 1, y: 0 }}\n          viewport={{ once: true }}\n          className="text-center"\n        >\n          <h2 className="text-4xl font-bold mb-4" style={{ color: "var(--color-text)" }}>\n            {props.headline || props.title || "${s.type} Section"}\n          </h2>\n          <p className="text-lg opacity-70 mb-8">\n            {props.subheadline || props.description || "Generated by BuildAI.Sites"}\n          </p>\n          {props.cta && (\n            <button className="px-8 py-3 rounded-full font-semibold text-white" style={{ background: "var(--color-primary)" }}>\n              {props.cta}\n            </button>\n          )}\n        </motion.div>\n      </div>\n    </section>\n  )\n}`).join("\n\n")}\n\nexport default function Home() {\n  return (\n    <main>\n${sectionComponents}\n    </main>\n  )\n}`,
  }
}

async function generateZip(projectName: string, files: Record<string, string>): Promise<Uint8Array> {
  const centralDirectory: Buffer[] = []
  const localFileHeaders: Buffer[] = []
  let offset: number = 0

  for (const [filePath, content] of Object.entries(files)) {
    const data = Buffer.from(content)
    const crc = crc32(data)
    const fileName = Buffer.from(filePath)

    const localHeader = Buffer.alloc(30 + fileName.length + data.length)
    localHeader.writeUInt32LE(0x04034b50, 0)
    localHeader.writeUInt16LE(20, 4)
    localHeader.writeUInt16LE(0, 6)
    localHeader.writeUInt16LE(0, 8)
    localHeader.writeUInt16LE(8, 10)
    localHeader.writeUInt16LE(0, 12)
    localHeader.writeUInt32LE(crc, 14)
    localHeader.writeUInt32LE(data.length, 18)
    localHeader.writeUInt32LE(data.length, 22)
    localHeader.writeUInt16LE(fileName.length, 26)
    fileName.copy(localHeader, 30)
    data.copy(localHeader, 30 + fileName.length)

    localFileHeaders.push(localHeader)

    const centralEntry = Buffer.alloc(46 + fileName.length)
    centralEntry.writeUInt32LE(0x02014b50, 0)
    centralEntry.writeUInt16LE(20, 4)
    centralEntry.writeUInt16LE(20, 6)
    centralEntry.writeUInt16LE(0, 8)
    centralEntry.writeUInt16LE(8, 10)
    centralEntry.writeUInt16LE(0, 12)
    centralEntry.writeUInt32LE(crc, 16)
    centralEntry.writeUInt32LE(data.length, 20)
    centralEntry.writeUInt32LE(data.length, 24)
    centralEntry.writeUInt16LE(fileName.length, 28)
    centralEntry.writeUInt16LE(0, 30)
    centralEntry.writeUInt16LE(0, 32)
    centralEntry.writeUInt32LE(0, 34)
    centralEntry.writeUInt32LE(0, 38)
    centralEntry.writeUInt32LE(offset, 42)
    fileName.copy(centralEntry, 46)

    centralDirectory.push(centralEntry)
    offset += localHeader.length
  }

  const eocd = Buffer.alloc(22)
  eocd.writeUInt32LE(0x06054b50, 0)
  eocd.writeUInt16LE(0, 4)
  eocd.writeUInt16LE(0, 6)
  const fileCount = Object.keys(files).length
  eocd.writeUInt16LE(fileCount, 8)
  eocd.writeUInt16LE(fileCount, 10)
  eocd.writeUInt32LE(Buffer.concat(centralDirectory).length, 12)
  eocd.writeUInt32LE(offset, 16)
  eocd.writeUInt16LE(0, 20)

  const result = new Uint8Array(Buffer.concat([...localFileHeaders, ...centralDirectory, eocd]))
  return result
}

function crc32(data: Buffer | Uint8Array): number {
  let crc = 0xffffffff
  for (let i = 0; i < data.length; i++) {
    crc ^= data[i]
    for (let j = 0; j < 8; j++) {
      crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0)
    }
  }
  return (crc ^ 0xffffffff) >>> 0
}
