"use client"

import { Suspense, useState, useCallback } from "react"
import { useSearchParams, useRouter } from "next/navigation"
import { ArrowLeft, Monitor, Smartphone, Tablet, Download, Share2, Globe, Eye, Code2, Loader2, Check, Copy } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { useStore } from "@/lib/store"

function PreviewContent() {
  const searchParams = useSearchParams()
  const router = useRouter()
  const { users } = useStore()
  const [device, setDevice] = useState<"desktop" | "tablet" | "mobile">("desktop")
  const [activeTab, setActiveTab] = useState<"preview" | "code">("preview")
  const [copied, setCopied] = useState(false)
  const [downloading, setDownloading] = useState(false)

  const projectId = searchParams.get("id")

  const allProjects = users.flatMap((u) => u.projects)
  const project = allProjects.find((p) => p.id === projectId)

  const devices = [
    { id: "desktop" as const, icon: Monitor, label: "Desktop" },
    { id: "tablet" as const, icon: Tablet, label: "Tablet" },
    { id: "mobile" as const, icon: Smartphone, label: "Mobile" },
  ]

  const handleDownload = useCallback(async () => {
    if (!project) return
    setDownloading(true)
    try {
      const res = await fetch("/api/download", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          project: {
            name: project.name,
            type: project.type,
            prompt: project.prompt,
            theme: {
              colors: { primary: "#7B3FE4", secondary: "#06B6D4", background: "#0b0e14", surface: "#131720", text: "#ffffff", muted: "#8b8fa3" },
              fonts: { display: "Inter", body: "Inter" },
            },
            pages: [{
              path: "/",
              sections: [
                { type: "Hero", props: { headline: project.name, subheadline: project.prompt, ctaPrimary: "Get Started", ctaSecondary: "Learn More" } },
                { type: "Features", props: { items: [{ title: "AI-Powered", description: "Generated by BuildAI.Sites" }, { title: "Fast", description: "Optimized for speed" }, { title: "Modern", description: "Beautiful design" }] } },
                { type: "CTA", props: { headline: "Ready to Start?", cta: "Get Started Free" } },
              ],
            }],
          },
        }),
      })
      if (!res.ok) throw new Error("Download failed")
      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = `${project.name.replace(/\s+/g, "-").toLowerCase()}.zip`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error("Download error:", err)
    } finally {
      setDownloading(false)
    }
  }, [project])

  const handleShare = useCallback(async () => {
    if (!project) return
    const url = `${window.location.origin}/preview?id=${project.id}`
    try {
      await navigator.clipboard.writeText(url)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      prompt("Copy this link:", url)
    }
  }, [project])

  if (!project) {
    return (
      <div className="min-h-[calc(100vh-4rem)] flex items-center justify-center">
        <div className="text-center animate-fade-in">
          <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-replit-card">
            <Eye className="h-8 w-8 text-replit-muted" />
          </div>
          <h2 className="text-xl font-semibold text-replit-text mb-2">Project not found</h2>
          <p className="text-sm text-replit-muted mb-6">The project you're looking for doesn't exist.</p>
          <Button onClick={() => router.push("/dashboard")}>
            <ArrowLeft className="mr-2 h-4 w-4" /> Back to Dashboard
          </Button>
        </div>
      </div>
    )
  }

  const generatedCode = `// Project: ${project.name}
// Type: ${project.type === "LANDING_PAGE" ? "Landing Page" : "Website"}
// Prompt: ${project.prompt}
// Generated by BuildAI.Sites

export default function Home() {
  return (
    <main className="min-h-screen bg-[#0b0e14] text-white">
      <section className="text-center py-24 px-4">
        <h1 className="text-5xl font-bold mb-4">${project.name}</h1>
        <p className="text-[#8b8fa3] text-lg max-w-xl mx-auto mb-8">
          ${project.prompt.split(",")[0] || "Built with AI"}
        </p>
        <div className="flex items-center justify-center gap-3">
          <button className="px-6 py-2.5 rounded-lg bg-[#7b3fe4] text-white font-medium">
            Get Started
          </button>
          <button className="px-6 py-2.5 rounded-lg border border-[#2a2f3f] text-white font-medium">
            Learn More
          </button>
        </div>
      </section>
    </main>
  )
}`

  return (
    <div className="min-h-[calc(100vh-4rem)]">
      <div className="border-b border-replit-border bg-replit-bg/80 backdrop-blur-xl">
        <div className="mx-auto max-w-7xl px-4">
          <div className="flex items-center justify-between h-14">
            <div className="flex items-center gap-3">
              <Button variant="ghost" size="icon" onClick={() => router.back()}>
                <ArrowLeft className="h-4 w-4" />
              </Button>
              <div>
                <h2 className="text-sm font-semibold text-replit-text">{project.name}</h2>
                <p className="text-xs text-replit-muted">{project.type === "LANDING_PAGE" ? "Landing Page" : "Website"}</p>
              </div>
              <Badge variant="success">Ready</Badge>
            </div>

            <div className="flex items-center gap-2">
              {devices.map((d) => (
                <button
                  key={d.id}
                  onClick={() => setDevice(d.id)}
                  className={`p-2 rounded-lg transition-all ${device === d.id ? "bg-replit-card text-replit-accent" : "text-replit-muted hover:text-replit-text"}`}
                >
                  <d.icon className="h-4 w-4" />
                </button>
              ))}
              <div className="w-px h-5 bg-replit-border mx-1" />
              <Button variant="ghost" size="sm" onClick={handleDownload} disabled={downloading}>
                <Download className="mr-1.5 h-4 w-4" /> {downloading ? "..." : "Download"}
              </Button>
              <Button variant="ghost" size="sm" onClick={handleShare}>
                {copied ? <Check className="mr-1.5 h-4 w-4 text-replit-green" /> : <Share2 className="mr-1.5 h-4 w-4" />}
                {copied ? "Copied!" : "Share"}
              </Button>
              <Button size="sm" onClick={handleDownload}>
                <Globe className="mr-1.5 h-4 w-4" /> Deploy
              </Button>
            </div>
          </div>
        </div>
      </div>

      <div className="mx-auto max-w-7xl px-4 py-6">
        <div className="flex gap-2 mb-6">
          <button
            onClick={() => setActiveTab("preview")}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${
              activeTab === "preview" ? "bg-replit-accent text-white" : "bg-replit-card text-replit-muted hover:text-replit-text"
            }`}
          >
            <Eye className="h-4 w-4" /> Preview
          </button>
          <button
            onClick={() => setActiveTab("code")}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${
              activeTab === "code" ? "bg-replit-accent text-white" : "bg-replit-card text-replit-muted hover:text-replit-text"
            }`}
          >
            <Code2 className="h-4 w-4" /> Code
          </button>
        </div>

        {activeTab === "preview" ? (
          <div className="flex justify-center">
            <div
              className={`relative rounded-2xl overflow-hidden border border-replit-border bg-replit-card transition-all duration-500 ${
                device === "desktop" ? "w-full max-w-5xl aspect-video" : device === "tablet" ? "w-[600px] aspect-[4/3]" : "w-[320px] aspect-[9/19]"
              }`}
            >
              <div className="absolute top-3 left-3 flex gap-1.5 z-10">
                <div className="w-3 h-3 rounded-full bg-replit-red" />
                <div className="w-3 h-3 rounded-full bg-replit-amber" />
                <div className="w-3 h-3 rounded-full bg-replit-green" />
              </div>
              <div className="w-full h-full overflow-y-auto p-6 pt-10">
                <div className="text-center mb-8">
                  <h1 className="text-3xl sm:text-4xl font-bold text-replit-text mb-3">{project.name}</h1>
                  <p className="text-lg text-replit-muted max-w-xl mx-auto">{project.prompt}</p>
                  <div className="flex items-center justify-center gap-3 mt-6">
                    <button className="px-6 py-2.5 rounded-lg bg-replit-accent text-white text-sm font-semibold hover:bg-replit-accent-hover transition-all">
                      Get Started
                    </button>
                    <button className="px-6 py-2.5 rounded-lg border border-replit-border text-replit-text text-sm font-semibold hover:bg-replit-hover transition-all">
                      Learn More
                    </button>
                  </div>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
                  {["AI-Powered", "Fast Performance", "Modern Design"].map((feature) => (
                    <div key={feature} className="p-4 rounded-xl bg-replit-surface border border-replit-border text-center">
                      <h3 className="text-sm font-semibold text-replit-text mb-1">{feature}</h3>
                      <p className="text-xs text-replit-muted">Generated by AI for {project.name}</p>
                    </div>
                  ))}
                </div>
                <div className="text-center">
                  <h2 className="text-2xl font-bold text-replit-text mb-2">Ready to Start?</h2>
                  <button className="px-8 py-3 rounded-lg bg-replit-accent text-white font-semibold hover:bg-replit-accent-hover transition-all">
                    Get Started Free
                  </button>
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div className="rounded-2xl border border-replit-border bg-replit-card overflow-hidden">
            <div className="flex items-center justify-between px-4 py-3 border-b border-replit-border">
              <div className="flex items-center gap-2">
                <Code2 className="h-4 w-4 text-replit-muted" />
                <span className="text-sm text-replit-muted">Source Code</span>
              </div>
              <div className="flex items-center gap-2">
                <Button variant="ghost" size="sm" onClick={() => { navigator.clipboard.writeText(generatedCode); setCopied(true); setTimeout(() => setCopied(false), 2000) }}>
                  {copied ? <Check className="mr-1.5 h-4 w-4 text-replit-green" /> : <Copy className="mr-1.5 h-4 w-4" />}
                  {copied ? "Copied!" : "Copy"}
                </Button>
                <Button variant="ghost" size="sm" onClick={handleDownload} disabled={downloading}>
                  <Download className="mr-1.5 h-4 w-4" /> {downloading ? "..." : "Download ZIP"}
                </Button>
              </div>
            </div>
            <div className="p-4">
              <div className="rounded-xl bg-replit-bg p-4 overflow-x-auto">
                <pre className="text-xs text-replit-muted font-mono leading-relaxed whitespace-pre">{generatedCode}</pre>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default function Preview() {
  return (
    <Suspense fallback={
      <div className="min-h-[calc(100vh-4rem)] flex items-center justify-center">
        <Loader2 className="h-8 w-8 text-replit-accent animate-spin" />
      </div>
    }>
      <PreviewContent />
    </Suspense>
  )
}
